export const surpriseMePrompts = [
    'an armchair in the shape of an avocado',
    'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
    'teddy bears shopping for groceries in Japan, ukiyo-e',
    'an oil painting by Matisse of a humanoid robot playing chess',
    'panda mad scientist mixing sparkling chemicals, digital art',
    "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
    '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
    'an astronaut lounging in a tropical resort in space, vaporwave',
    'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
    'a stained glass window depicting a hamburger and french fries',
    'a pencil and watercolor drawing of a bright city in the future with flying cars',
    'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
    'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
    '"a sea otter with a pearl earring" by Johannes Vermeer',
    'an oil pastel drawing of an annoyed cat in a spaceship',
    'a painting of a fox in the style of Starry Night',
    'a bowl of soup that looks like a monster, knitted out of wool',
    'A plush toy robot sitting against a yellow wall',
    'A synthwave style sunset above the reflecting water of the sea, digital art',
    'Two futuristic towers with a skybridge covered in lush foliage, digital art',
    'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
    'A comic book cover of a superhero wearing headphones',
    'A centered explosion of colorful powder on a black background',
    'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
    'A photo of a white fur monster standing in a purple room',
    "A photo of Michelangelo's sculpture of David wearing headphones djing",
    'A Samurai riding a Horse on Mars, lomography.',
    'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
    'A realistic photograph of a young woman with blue eyes and blonde hair',
    'A man standing in front of a stargate to another dimension',
    'Spongebob Squarepants in the Blair Witch Project',
    'A velociraptor working at a hotdog stand, lomography',
    'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
    'A BBQ that is alive, in the style of a Pixar animated movie',
    'A futuristic cyborg dance club, neon lights',
    'The long-lost Star Wars 1990 Japanese Anime',
    'A hamburger in the shape of a Rubik’s cube, professional food photography',
    'A Synthwave Hedgehog, Blade Runner Cyberpunk',
    'An astronaut encountering an alien life form on a distant planet, photography',
    'A Dinosaur exploring Cape Town, photography',
    'A Man falling in Love with his Computer, digital art',
    'A photograph of a cyborg exploring Tokyo at night, lomography',
    'Dracula walking down the street of New York City in the 1920s, black and white photography',
    'Synthwave aeroplane',
    'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
    'A Space Shuttle flying above Cape Town, digital art',
    "A flamingo in a top hat and bowtie",
    "A house made entirely of ice cream",
    "A city skyline at night with a full moon in the background",
    "A giant treehouse in the middle of a forest",
    "A hot air balloon flying over a field of sunflowers",
    "A dragon with butterfly wings",
    "A mermaid sitting on a rock in the ocean",
    "A robot playing guitar on a stage",
    "A panda wearing a crown and sitting on a throne",
    "A rainbow-colored waterfall",
    "A castle floating in the clouds",
    "A spaceship exploring a distant planet",
    "A floating city made of glass",
    "A unicorn eating pizza",
    "A circus tent with acrobats performing",
    "A magical garden with talking flowers",
    "A superhero riding a bicycle",
    "A monkey wearing a top hat and monocle",
    "A giraffe in a tuxedo",
    "A pirate ship on the high seas",
    "A train made entirely of candy",
    "A wizard casting a spell",
    "A giant snail racing a tortoise",
    "A frog playing chess with a rabbit",
    "A witch flying on a broomstick",
    "A roller coaster through a haunted forest",
    "A group of penguins playing soccer",
    "A snake with wings",
    "A giant squid attacking a ship",
    "A bear wearing a bowtie and suspenders",
    "A submarine exploring an underwater city",
    "A spiderweb made of gold",
    "A group of animals having a picnic",
    "A dinosaur riding a bicycle",
    "A rocket launching into space",
    "A dolphin jumping over a rainbow",
    "A robot walking a dog",
    "A castle made of crystal",
    "A bird wearing a top hat and reading a book",
    "A unicorn with a rainbow mane",
    "A wizard riding a dragon",
    "A mermaid riding a seahorse",
    "A tree with a face and arms",
    "A bunny wearing a bowtie and carrying a briefcase",
    "A lion in a suit and tie",
    "A dragon with a treasure hoard",
    "A spaceship flying through a wormhole",
    "A giant robot fighting a giant monster",
    "A city made entirely of clouds",
    "A giant octopus playing the piano",
    "A castle surrounded by a moat of lava",
    "A dinosaur hatching from an egg",
    "A unicorn playing the guitar",
    "A monkey riding a unicycle",
    "A robot playing chess with a human",
    "A giant robot serving coffee at a cafe",
    "A city skyline with a rainbow in the background",
    "A wizard riding a unicorn",
    "A group of animals having a tea party",
    "A dragon breathing fire",
    "A mermaid with a pearl necklace",
    "A robot washing dishes",
    "A bird wearing a bowtie and flying a plane",
    "A castle made of sand",
    "A lion with wings",
    "A robot playing basketball",
    "A giant robot building a city",
    "A dinosaur wearing a fedora",
    "A unicorn with butterfly wings",
    "A monkey playing a guitar",
    "A robot playing the drums",
    "A castle made of ice",
    "A robot serving ice cream",
    "A bird wearing a hat and reading a newspaper",
    "A lion in a top hat and tails"
];